[package]
name = "app_de_rust"
version = "0.1.0"
authors = ["Tu javier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
